### ISSUE TITLE
Failed to compile Mshdist with gcc version 14.1 (works with version 13.3)

### ISSUE THREAD

**Issue by ngrigri** [ISCDtoolbox/Mshdist#12]
Hello,

I get a compilation error when I use gcc version 14.1, whereas the code is compiled to completion with version 13.3 of the same compiler.

The error message is: 
```
$HOME/ISCDtoolbox/Mshdist/sources/mshdis1_s.c: In function 'iniencdomain_s':
$HOME//ISCDtoolbox/Mshdist/sources/mshdis1_s.c:240:36: error: passing argument 4 of 'distpt_s' from incompatible pointer type [-Wincompatible-pointer-types]
  240 |             dd = distpt_s(pa,pb,p1,&proj);
      |                                    ^~~~~
      |                                    |
      |                                    char *
In file included from $HOME//ISCDtoolbox/Mshdist/sources/mshdis1_s.c:1:
$HOME/ISCDtoolbox/Mshdist/sources/mshdist.h:174:38: note: expected 'int *' but argument is of type 'char *'
  174 | double distpt_s(pPoint,pPoint,pPoint,int*);
      |                                      ^~~~
$HOME//ISCDtoolbox/Mshdist/sources/mshdis1_s.c:249:36: error: passing argument 4 of 'distpt_s' from incompatible pointer type [-Wincompatible-pointer-types]
  249 |             dd = distpt_s(pa,pb,p2,&proj);
      |                                    ^~~~~
      |                                    |
      |                                    char *
$HOME//ISCDtoolbox/Mshdist/sources/mshdist.h:174:38: note: expected 'int *' but argument is of type 'char *'
  174 | double distpt_s(pPoint,pPoint,pPoint,int*);
      |                                      ^~~~
$HOME//ISCDtoolbox/Mshdist/sources/mshdis1_s.c:292:34: error: passing argument 4 of 'distpt_s' from incompatible pointer type [-Wincompatible-pointer-types]
  292 |           dd = distpt_s(pa,pb,p0,&proj);
      |                                  ^~~~~
      |                                  |
      |                                  char *
$HOME//ISCDtoolbox/Mshdist/sources/mshdist.h:174:38: note: expected 'int *' but argument is of type 'char *'
  174 | double distpt_s(pPoint,pPoint,pPoint,int*);
      |                                      ^~~~
make[2]: *** [CMakeFiles/libMshdist.dir/build.make:174: CMakeFiles/libMshdist.dir/sources/mshdis1_s.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/libMshdist.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
And the compiler versions are (micromamba environment):

```
gcc                            14.1.0          h6f9ffa1_1             conda-forge
gfortran                       14.1.0          h6f9ffa1_1             conda-forge
gxx                            14.1.0          h6f9ffa1_1             conda-forge

```

Tanks.

**Comment by ngrigri** [comment]
The problem seems to be an incompatible pointer type. This is identified as one of the gcc-14 changes at https://gcc.gnu.org/gcc-14/porting_to.html

**Comment by Algiane** [comment]
Hi,

Thanks for the feedback.
A fix is proposed in #13.

Best
